import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e5eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        "on-surface": "#0b1c30",
        "on-surface-variant": "#45464d",
        "inverse-surface": "#213145",
        "inverse-on-surface": "#eaf1ff",
        outline: "#76777d",
        "outline-variant": "#c6c6cd",
        "surface-tint": "#565e74",
        primary: "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#131b2e",
        "on-primary-container": "#7c839b",
        "inverse-primary": "#bec6e0",
        secondary: "#4b41e1",
        "on-secondary": "#ffffff",
        "secondary-container": "#645efb",
        "on-secondary-container": "#fffbff",
        tertiary: "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#111c2d",
        "on-tertiary-container": "#79849a",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#dae2fd",
        "primary-fixed-dim": "#bec6e0",
        "on-primary-fixed": "#131b2e",
        "on-primary-fixed-variant": "#3f465c",
        "secondary-fixed": "#e2dfff",
        "secondary-fixed-dim": "#c3c0ff",
        "on-secondary-fixed": "#0f0069",
        "on-secondary-fixed-variant": "#3323cc",
        "tertiary-fixed": "#d8e3fb",
        "tertiary-fixed-dim": "#bcc7de",
        "on-tertiary-fixed": "#111c2d",
        "on-tertiary-fixed-variant": "#3c475a",
        background: "#f8f9ff",
        "on-background": "#0b1c30",
        "surface-variant": "#d3e4fe",
        success: "#059669",
        warning: "#d97706",
        critical: "#e11d48",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        gutter: "1.5rem",
        "gutter-mobile": "1rem",
        "gutter-desktop": "2rem",
        margin: "1.5rem",
        "margin-mobile": "1rem",
        "margin-desktop": "3rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
      },
      maxWidth: {
        studio: "1440px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
        display: [
          "var(--font-plus-jakarta)",
          "Plus Jakarta Sans",
          "system-ui",
          "sans-serif",
        ],
        "display-hero": ["var(--font-plus-jakarta)", "Plus Jakarta Sans"],
        "display-hero-mobile": [
          "var(--font-plus-jakarta)",
          "Plus Jakarta Sans",
        ],
        "headline-lg": ["var(--font-plus-jakarta)", "Plus Jakarta Sans"],
        "headline-lg-mobile": [
          "var(--font-plus-jakarta)",
          "Plus Jakarta Sans",
        ],
        "headline-md": ["var(--font-plus-jakarta)", "Plus Jakarta Sans"],
        "headline-sm": ["var(--font-plus-jakarta)", "Plus Jakarta Sans"],
        "body-lg": ["var(--font-inter)", "Inter"],
        "body-md": ["var(--font-inter)", "Inter"],
        "body-sm": ["var(--font-inter)", "Inter"],
        "label-lg": ["var(--font-inter)", "Inter"],
        "label-md": ["var(--font-inter)", "Inter"],
        "label-caps": ["var(--font-inter)", "Inter"],
        "price-hero": ["var(--font-plus-jakarta)", "Plus Jakarta Sans"],
        "price-card": ["var(--font-plus-jakarta)", "Plus Jakarta Sans"],
      },
      fontSize: {
        "display-hero": [
          "56px",
          { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "700" },
        ],
        "display-hero-mobile": [
          "36px",
          { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "700" },
        ],
        "headline-lg": [
          "36px",
          { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "headline-md": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" },
        ],
        "headline-sm": [
          "20px",
          { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" },
        ],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" },
        ],
        "label-caps": [
          "11px",
          { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "700" },
        ],
        "price-hero": [
          "28px",
          { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "price-card": ["16px", { lineHeight: "22px", fontWeight: "600" }],
      },
      boxShadow: {
        level1:
          "0 4px 20px -2px rgba(15, 23, 42, 0.05), 0 2px 6px -1px rgba(15, 23, 42, 0.02)",
        level2:
          "0 12px 32px -4px rgba(15, 23, 42, 0.08), 0 4px 12px -2px rgba(15, 23, 42, 0.03)",
        level3: "-16px 0 48px rgba(15, 23, 42, 0.12)",
        header: "0 1px 8px rgba(0, 0, 0, 0.04)",
      },
      container: {
        center: true,
        screens: {
          "2xl": "1440px",
        },
      },
    },
  },
  plugins: [],
};

export default config;
